#!/usr/bin/env bun
/**
 * Add Qwen3-Embedding-8B to OpenRouter provider in models-snapshot.ts
 */

import fs from "fs"
import path from "path"

const snapshotPath = path.join(import.meta.dir, "../src/provider/models-snapshot.ts")

// Read the current snapshot
const content = fs.readFileSync(snapshotPath, "utf-8")

// Extract the JSON data (it's exported as `export const snapshot = {...}`)
const jsonMatch = content.match(/export const snapshot = ({[\s\S]+})/)
if (!jsonMatch) {
  console.error("Could not find snapshot export in models-snapshot.ts")
  process.exit(1)
}

const snapshotData = JSON.parse(jsonMatch[1])

// Add Qwen3-Embedding-8B to OpenRouter models
if (!snapshotData.openrouter) {
  console.error("OpenRouter provider not found in snapshot")
  process.exit(1)
}

const qwenEmbeddingModel = {
  id: "qwen/qwen3-embedding-8b",
  name: "Qwen3 Embedding 8B",
  family: "text-embedding",
  attachment: false,
  reasoning: false,
  tool_call: false,
  structured_output: false,
  temperature: false,
  knowledge: "2025-10",
  release_date: "2026-01-10",
  last_updated: "2026-02-21",
  modalities: {
    input: ["text"],
    output: ["text"],
  },
  open_weights: true,
  cost: {
    input: 0.01,
    output: 0,
  },
  limit: {
    context: 32768,
    input: 32768,
    output: 0,
  },
}

snapshotData.openrouter.models["qwen/qwen3-embedding-8b"] = qwenEmbeddingModel

// Write back
const newContent = `// Auto-generated by build.ts - do not edit\n// Manual addition: Qwen3-Embedding-8B added ${new Date().toISOString()}\nexport const snapshot = ${JSON.stringify(snapshotData, null, 2)}\n`

fs.writeFileSync(snapshotPath, newContent, "utf-8")

console.log("✅ Added qwen/qwen3-embedding-8b to OpenRouter provider")
console.log("   Dimensions: 4096")
console.log("   Cost: $0.01/M tokens")
console.log("   Context: 32,768 tokens")
